spring:
  application:
    name: diplomski-be
  datasource:
    url: jdbc:postgresql://localhost:5432/diplomski-postgres
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate # zelimo da Flyway bude jedini vlasnik schema promena
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

app:
  invitation-token: # invitation-based account activation
    duration-in-hours: 24

